### ISSUE TITLE
🎃 Hacktoberfest Opportunity : More tests need to be written

### ISSUE THREAD

**Issue by JakenHerman** [JakenHerman/kcats#3]
As of right now, the tests aren't very in-depth. In the folder tests, the file `test.js` needs to be updated to **extensively** test out the package.

The test framework I'm using is [Mochajs](http://mochajs.org/) if documentation is needed.

Once tests are created, just run `npm test`, as the `package.json` file already specifies the command to be `mocha tests/test.js`.

This should be a fairly easy/fun project to work on, but I'd like to extend a PR opportunity to someone new to FLOSS so they can get that hacktoberfest t-shirt.

Happy Hacking!

**Comment by cbsorrilha** [comment]
Hey, i want to help. There are some tests implemented on master. How more we'll need?

**Comment by JakenHerman** [comment]
@cbsorrilha the project just needs to be tested more with cases having multiple stacks. As of right now, most of the tests are assuming that `this._num_stacks = 1`, so most of the operations aren't getting to really be tested out with multiple stacks.

**Comment by JakenHerman** [comment]
@cbsorrilha as of right now `._reset()`, `._isfull()`, `._pop()`, and  `._peek()` are using test-case of `var tests = new kcats(size);`, which means that `this._num_stacks` defaults to 1, meaning there is only one stack. We need to leave those tests in place, but also add a new case like `var tests2 = new kcats(size, number-of-stacks)`, then run some tests to make sure that the operations work on any number of stacks.

**Comment by cbsorrilha** [comment]
I see...
So let's create tests with:

```
this._num_stacks = 5;
this._num_stacks = 100;
this._num_stacks = 1000;
```

or something like this?

**Comment by JakenHerman** [comment]
@cbsorrilha right, and you do that by passing in `5`, `100`, or `1000` as the second parameter. For example, if you want to allocate 50 storage spaces broken up into 2 different stacks, you would say `var test = new kcats(50, 2);`, and this would mean that stack 1 gets space 0-24, and stack 2 gets space 25-49

**Comment by babhishek21** [comment]
Try using progressively large random numbers as arguments.

**Comment by cbsorrilha** [comment]
How can i test every stack in an array of stacks, generated by a random number?

**Comment by chrisonntag** [comment]
Hey, i'm simultaneously working on this. You could use mochas forEach() function for iterating through an array with number-of-stacks values in it and then using a for-loop in order to fill and test each stack i guess.

``` javascript
var testNumbers = [10, 100];

testNumbers.forEach(function(num) {
    it('does something with ' + num + ' stacks',
    function() {
      var tests = new kcats(num, num);
      for(var i=0; i < num - 1; i++) {
          tests._push("fill", i);

          var isEmptyFalse = tests._isEmpty(i);
          assert.equal(isEmptyFalse, false);
          tests._reset(i);
          var isEmptyTrue = tests._isEmpty(i);
          assert.equal(isEmptyTrue, true);
      }
    });
});
```

**Comment by stephnr** [comment]
Need anymore help here guys? @cbsorrilha @chrisonntag 

![](https://media.giphy.com/media/jyDc9mR1kIlDW/giphy.gif)
