### ISSUE TITLE
Throw error when num_stacks > max_len

### ISSUE THREAD

**Issue by JakenHerman** [JakenHerman/kcats#7]
For example, if we tried to create a stack "tester" as `var tester = new kcats(100, 102);`, we can never properly allocate 102 stacks to 100 spaces of memory. We have to make sure it's something like `var tester = new kcats(100, 50);`, which would work. In this case we would have 50 stacks of 2-spaces of storage each.

**Comment by zeokav** [comment]
I'd like to take this up!

**Comment by JakenHerman** [comment]
@zeokav go for it!

**Comment by zeokav** [comment]
Please review my pull request and let me know if anything else is required. 😄

**Comment by nunofaria11** [comment]
Hi there, I would like to make a slight improvement to @zeokav did and add a unit test for it https://github.com/JakenHerman/kcats/pull/11 hope you don't mind ;) happy hackin
